### ISSUE TITLE
set start month in knn_space_time_disagg()

### ISSUE THREAD

**Issue by rabutler-usbr** [rabutler-usbr/knnstdisagg#11]
for the rownames of the output, we currently assume that the data are always starting in January. 

need a way to specify this.

could:
1 - require that the `mon_flow` have rownames or a columns with some monthly info
2 - add another argument that just states the start month

--------------
**plotting**

- [x] add start_month to `knnst` objects
- [x] nothing changes on monthly stats, just need to update `get_pattern_flow_data_df()` so that it uses `start_month` and does not assume it starts in January
- [x] new function to compute "agg_year" based on start_month. Idea being that we assume that if data start in a certain month, that is the beginning of the "agg_year", e.g., water year or fiscal year.
- [x] update `get_ann_plot_stats()` to sum by agg_year and not by year. 
- [x] update plotting order of monthly boxplots to also be based on start_month
- [x] new test - plot data with 2 different start months (use n = 1), get the annual data out of the ggplot object, it should be the same

**Comment by rabutler** [comment]
will need to update the plotting of historical data in `plot.knnst()`

may also want to add in option to change the order the months are shown. Right now it's always Jan - Dec

**Comment by rabutler-usbr** [comment]
Decided to go with option 2 - added `start_month` argument to `knn_space_time_disagg()`. It seemed a bit complicated to require a certain format of row names at this point.
